behaviors:
  Tennis:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
      beta_schedule: constant
      epsilon_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 4
      vis_encode_type: simple
      goal_conditioning_type: hyper
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      gail: 
        strength: 0.8
        demo_path: demo/Demo4.demo
    behavioral_cloning:
        strength: 0.8
        demo_path: demo/Demo4.demo
    keep_checkpoints: 1
    checkpoint_interval: 100000
    max_steps: 1000000
    time_horizon: 1000
    summary_freq: 5000
    threaded: false
    self_play:
      save_steps: 5000
      team_change: 10000
      swap_steps: 2000
      window: 100
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
