behaviors:
  Tennis:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
      beta_schedule: constant
      epsilon_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 6
      vis_encode_type: simple
      goal_conditioning_type: hyper
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    #  gail: 
    #    strength: 0.8
    #    demo_path: Demos/TennisDemo.demo
    #behavioral_cloning:
    #    strength: 0.8
    #    demo_path: Demos/TennisDemo.demo
    keep_checkpoints: 1
    checkpoint_interval: 1000000
    max_steps: 10000000
    time_horizon: 10000
    summary_freq: 15000
    threaded: false
    self_play:
      save_steps: 5000
      #team_change: 50000
      swap_steps: 30000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1500.0
